AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
    Serverless application to respond to events from the IoT trigger and send to Splunk HTTP Event Collector (HEC).

    This SAM template creates the Lambda function with its IAM execution role, 

    Last Modified: 06 Oct, 2017
    Authors: Roy Arsan <roy@splunk.com>, Bill Bartlett <bbartlett@splunk.com>, Tarik Makota <tmak@amazon.com>

Parameters:
    IoTRule: 
      Type: "String"
      Description: "Name of a AWS IoT rule. In AWS IoT Console under 'Act' you'll have see your existing Rules"

    AwsIotSqlVersion:
      Type: "String"
      Description: "IoT SQL Version (if not sure leave as deafult)"
      Default: "2016-03-23"

    SplunkHttpEventCollectorURL:
      Type: "String"
      Description: "URL address of your Splunk HTTP event collector endpoint"

    SplunkHttpEventCollectorToken:
      Type: "String"
      Description: "Token of your Splunk HTTP event collector endpoint"

Outputs:
    SplunkIoTProcessorFunction:
      Description: "Splunk IoT Serverless Function"
      Value: !GetAtt IoTFunction.Arn

Resources:
  IoTFunction: 
    Type: AWS::Serverless::Function
    Properties: 
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./splunk-iot-processor.zip
      Policies: AWSLambdaBasicExecutionRole
      Description: Capture events from IOT topic and send to Splunk HTTP event collector
      MemorySize: 512
      Timeout: 10
      Environment:
          Variables:
            SPLUNK_HEC_URL: !Ref SplunkHttpEventCollectorURL
            SPLUNK_HEC_TOKEN: !Ref SplunkHttpEventCollectorToken
      Events: 
        IoT: 
          Type: IoTRule
          Properties: 
            AwsIotSqlVersion: !Ref AwsIotSqlVersion
            Sql: !Join [ "", [ "SELECT * FROM '", !Ref IoTRule, "/+'" ] ] 